repository:
  name: 'phpunit-attributes'
  description: '🧙 Additional attributes for tests with PHPUnit'
  topics: 'phpunit,testing,unit,test,attributes,php'
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: 'main'
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  # This will be handled by Renovate
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

# Labels for issues and pull requests
labels:
  - name: 'breaking'
    color: '#36454f'
    description: 'This introduces a breaking change'

  - name: 'bug'
    color: '#d73a4a'
    description: Something isn't working

  - name: 'dependencies'
    color: '#93cb4a'
    description: 'Updates project dependencies'

  - name: 'documentation'
    color: '#0075ca'
    description: 'Improvements or additions to documentation'

  - name: 'duplicate'
    color: '#cfd3d7'
    description: 'This issue or pull request already exists'

  - name: 'enhancement'
    color: '#a2eeef'
    description: 'New feature or request'

  - name: 'good first issue'
    color: '#7057ff'
    description: 'Good for newcomers'

  - name: 'help wanted'
    color: '#008672'
    description: 'Extra attention is needed'

  - name: 'invalid'
    color: '#e4e669'
    description: This doesn't seem right

  - name: 'maintenance'
    color: '#c0e596'
    description: 'Code base is being maintained'

  - name: 'question'
    color: '#d876e3'
    description: 'Further information is requested'

  - name: 'security'
    color: '#ef7da3'
    description: 'Contains security fixes'

  - name: 'wontfix'
    color: '#ffffff'
    description: 'This will not be worked on'

# Branch protection rules
branches:
  - name: 'main'
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - 'cgl'
          - 'Tests with Composer (PHP 8.1, PHPUnit 10 & highest dependencies)'
          - 'Tests with Composer (PHP 8.1, PHPUnit 10 & lowest dependencies)'
          - 'Tests with Composer (PHP 8.2, PHPUnit 10 & highest dependencies)'
          - 'Tests with Composer (PHP 8.2, PHPUnit 10 & lowest dependencies)'
          - 'Tests with Composer (PHP 8.2, PHPUnit 11 & highest dependencies)'
          - 'Tests with Composer (PHP 8.2, PHPUnit 11 & lowest dependencies)'
          - 'Tests with Composer (PHP 8.3, PHPUnit 10 & highest dependencies)'
          - 'Tests with Composer (PHP 8.3, PHPUnit 10 & lowest dependencies)'
          - 'Tests with Composer (PHP 8.3, PHPUnit 11 & highest dependencies)'
          - 'Tests with Composer (PHP 8.3, PHPUnit 11 & lowest dependencies)'
          - 'Tests with PHAR (PHP 8.1 & PHPUnit 10)'
          - 'Tests with PHAR (PHP 8.2 & PHPUnit 10)'
          - 'Tests with PHAR (PHP 8.2 & PHPUnit 11)'
          - 'Tests with PHAR (PHP 8.3 & PHPUnit 10)'
          - 'Tests with PHAR (PHP 8.3 & PHPUnit 11)'
          - 'Test coverage'
      enforce_admins: false
      required_linear_history: true
      restrictions: ~
