name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@0493ad446f3b35cfc9b7ed75330e91a6bd061728 # 1.1.7

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@0493ad446f3b35cfc9b7ed75330e91a6bd061728 # 1.1.7
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore

  composer-tests:
    name: 'Composer tests (PHP ${{ matrix.php-version }}, PHPUnit ${{ matrix.phpunit-version }} & ${{ matrix.dependencies }} dependencies)'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        phpunit-version: ["11", "12", "13"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.2"
            phpunit-version: "12"
          - php-version: "8.2"
            phpunit-version: "13"
          - php-version: "8.3"
            phpunit-version: "13"

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@0493ad446f3b35cfc9b7ed75330e91a6bd061728 # 1.1.7
    with:
      php-version: ${{ matrix.php-version }}
      dependencies: ${{ matrix.dependencies }}
      composer-options: --with=phpunit/phpunit:^${{ matrix.phpunit-version }}

  phar-tests:
    name: 'PHAR tests (PHP ${{ matrix.php-version }} & PHPUnit ${{ matrix.phpunit-version }})'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        phpunit-version: ["11", "12", "13"]
        exclude:
          - php-version: "8.2"
            phpunit-version: "12"
          - php-version: "8.2"
            phpunit-version: "13"
          - php-version: "8.3"
            phpunit-version: "13"

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@0493ad446f3b35cfc9b7ed75330e91a6bd061728 # 1.1.7
    with:
      php-version: ${{ matrix.php-version }}
      dependencies: ${{ matrix.dependencies }}
      phpunit-phar-version: ${{ matrix.phpunit-version }}
      phpunit-phar-flags: --no-coverage --configuration build/tests/phpunit.xml

  test-coverage:
    name: 'Test coverage'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    uses: eliashaeussler/gha/.github/workflows/composer-test-coverage.yaml@0493ad446f3b35cfc9b7ed75330e91a6bd061728 # 1.1.7
